### PR TITLE
Improve UI and UX

### PR DESCRIPTION
**Pull request by TobiGr**
This brings an improved design focusing mobile users, including colours and more buttons to help people be faster with it. I think the buttons are self-explaining :) The textareas will expand when needed.
We could also make the transform button to instantly copy the converted report to the clipboard, but I'd like to hear your thoughts first because copying something to the clipboard without a warning can have fatal consequences...

bildschirmfoto vom 2018-09-11 um 14 47 13

### CODE REVIEW

**Comment by TheAssassin** [comment]
Adding this repository to the web team.

**Comment by TheAssassin** [comment]
The "copy to clipboard" button should probably go below the lower input, right now I get the impression it copies the JSON to the clipboard.
Also, I think one "new issue" button is enough.

Can we increase the height of the input boxes? The content is most likely quite tall (it contains newlines). Not sure if that makes sense on mobile devices, though.

**Comment by TobiGr** [comment]
> The "copy to clipboard" button should probably go below the lower input, right now I get the impression it copies the JSON to the clipboard.
Also, I think one "new issue" button is enough.

Will do.

> Can we increase the height of the input boxes? The content is most likely quite tall (it contains newlines). Not sure if that makes sense on mobile devices, though.

I kept a maximum of 20 lines in the textareas which @theScrabi used.

**Comment by TheAssassin** [comment]
> I kept a maximum of 20 lines in the textareas which @theScrabi used.

Oh right they resize automatically when content is added.

**Comment by TobiGr** [comment]
@theScrabi Anything to add or is this good to merge?

**Comment by theScrabi** [comment]
No its good :)

**Comment by TheAssassin** [comment]
> We could also make the transform button to instantly copy the converted report to the clipboard, but I'd like to hear your thoughts first because copying something to the clipboard without a warning can have fatal consequences...

I think that's not the best UX. A button will work better.

Edit: screw you, Chromium... seems like my reply was delayed _a bit_...

**Pull request merged**
